version: '3'
services:
  web1:
    build: ./web1
    expose:
      - 5000
  web2:
    build: ./web2
    expose:
      - 5000
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web1
      - web2
